name: Python Package

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release' && success()

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Set execute permissions for the upload script
        run: chmod +x ./upload_to_pypi.sh

      - name: Publish to PyPI
        run: ./upload_to_pypi.sh
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

      - name: Set execute permissions for the github release manager script
        run: chmod +x ./github_release_manager.sh

      - name: Extract version and update GitHub release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./github_release_manager.sh
